name: Build-Test-Fmt

on: [push, pull_request]

jobs:
  build-test-fmt:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    
    - name: Build
      run: cd server && cargo build
      
    - name: Test
      run: cd server && cargo test --package circom-lsp
      
    - name: Fmt
      run: cd server && cargo fmt --package circom-lsp
